#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from MessageHandler import MessageHandler

class Router:
    """_summary_

    Returns:
        _type_: _description_
    """
    relations = {}
    sockets = {}
    ports = {}

    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        self.message_handler = MessageHandler(self)

        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            self.send(neighbor, json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}  }))

    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network])) #Shujun's

    def sendJson(self, network, message):
        self.sockets[network].sendto(json.dumps(message).encode('utf-8'), ('localhost', self.ports[network])) #modified

    def run(self):
        while True:
            # get sockets that are ready for reading, wait for up to 0.1 seconds
            # print("HERE", self.sockets.values())
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            # read from each ready socket
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                # identify the socket currently being read from
                for sock in self.sockets: 
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break # found
                msg = k.decode('utf-8')

                print("Received message '%s' from %s" % (msg, srcif))


                self.message_handler.handle_message(msg, srcif)
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
